- en: 【沃顿商学院】商业分析 全套课程（客户、运营、人力资源、会计） - P30：[P030]04_applications-roi - 知识旅行家 - BV1o54y1N7pm
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: '![](img/3aaac3cbf8f98628a4e150fba24448e8_0.png)'
  prefs: []
  type: TYPE_IMG
- en: 让我在接下来的五分钟左右的时间里简短地告诉你一些商业问题的样本，这就是为什么人们对分析如此兴奋，然后我要进入心脏和肉，这是今天一些公司的一些应用，所以这可能是我四处旅行和世界各地的公司交谈的时候。
  prefs: []
  type: TYPE_NORMAL
- en: 人们想要回答的最重要的问题之一，是广告归因问题，或者如果你想知道每个广告值多少钱，或者广告的阿ROI是什么，所以想象一下你坐在这里，在Coursera上收听这门营销分析课程，想象你说，你知道的。
  prefs: []
  type: TYPE_NORMAL
- en: 我有十万美元的预算用于公司的市场营销，我想把它花在电视上吗，我想把它花在收音机上吗，所以我想把它花在搜索引擎营销上，你如何计算出每一个的投资回报率，这是一个典型的应用区域的例子，人们花了很多时间思考。
  prefs: []
  type: TYPE_NORMAL
- en: 不幸的是，今天的艺术水平是不是艺术水平，今天常见的做法是所谓的最后一次点击归因，这是你做的最后一件让你获得荣誉的事情，换句话说，如果我买你的产品之前做的最后一件事是在这里，广播广告，嗯。
  prefs: []
  type: TYPE_NORMAL
- en: 一定是广播广告干的，但如果你真的想想这个逻辑，是什么让你听那个广播广告，而不是换车站，然后一天后你买，或者想象你在谷歌搜索，哪个或一个，你知道吗，如果有，使用你最喜欢的搜索引擎。
  prefs: []
  type: TYPE_NORMAL
- en: 想象一下使用谷歌或必应搜索，现在突然间你知道了外面的一系列选择，所以真正重要的是，归因是理解人们所看到的事物的整个路径，这里有一个我以前处理过的数据集的例子，让我们从数据集的末尾开始，让我们努力前进。
  prefs: []
  type: TYPE_NORMAL
- en: 假设您在一个站点上进行了转换，例如，嗯，我在这里给你举的例子是一个汽车网站，所以想象一下有人皈依了，这意味着他们实际上已经预约了测试，开车，不幸的是，在美国，你实际上不能在网上买车。
  prefs: []
  type: TYPE_NORMAL
- en: 但你实际上可以设计你的车，你可以把它寄给经销商报价，他们认为转换，但想象一下我对你的道路了如指掌，您在站点转换之前所做的，就像我知道你去埃德蒙兹，com并查看了一则广告，我知道你上过CNN。
  prefs: []
  type: TYPE_NORMAL
- en: com和你成为广告的目标，我知道你在凯利的蓝皮书上看到了一则广告，我知道你去谷歌搜索了，然后我知道你去了一个广告商网站，最后你实际上在那个网站上转换了，所以一天结束时，嗯上次点击属性，会说。
  prefs: []
  type: TYPE_NORMAL
- en: 把所有的功劳都归功于谷歌的点击通过，但那可能不对，所有这些事情，你之前看到的所有广告，这可能是导致你，实际上去谷歌，做那个搜索，去找广告商，最终再次单击，这是最重要的问题之一，另一个我喜欢研究的问题是。
  prefs: []
  type: TYPE_NORMAL
- en: 我实际上花了大约一年的时间在一个项目上，ESPN全球体育界的领导者，有点，嗯，这与2000年的双子世界杯有关，足球锦标赛，哪个是最大的，众所周知，我认为世界杯足球赛是世界上转播和收视率最高的赛事。
  prefs: []
  type: TYPE_NORMAL
- en: 他们想通过分析来回答的一个事件，是嗯，如果他们推出一个移动平台，这会蚕食他们的电视观看吗，它会蚕食在线流媒体的人吗，它会蚕食去PN的人吗，www。icj-cij。com，现在，这是一个重要的商业问题。
  prefs: []
  type: TYPE_NORMAL
- en: 我相信你们中的许多人也面临着这个问题，如果一个频道蚕食另一个频道，那可能不是坏事，如果另一个频道更有利可图，但是手机广告的价值比其他广告低得多，你可以收取更多的电视广告比你可以收取更多的移动广告。
  prefs: []
  type: TYPE_NORMAL
- en: 如果移动广告在蚕食，那是件坏事，所以这是ESPN想知道的一个问题，如果他们推出一个观看世界杯的移动频道，会吃人吗，这就是市场营销中所谓的GRPS的基本问题，这就是所谓的总评分点。
  prefs: []
  type: TYPE_NORMAL
- en: ESPN想了解的是他们有两个想法，他们想接触到尽可能多的客户，在这种情况下，世界杯的内容和频率，他们希望这些客户尽可能多地观看内容，所以如果你喜欢，有多少家庭会观看任何内容和频率，是内容的体积。
  prefs: []
  type: TYPE_NORMAL
- en: 你把这些东西相乘，你现在有抓地力了，ESPN为什么关心GRPS，因为他们收广告费，他们的抓地力就越多，他们能收的广告费就越多，所以这是一个分析问题，那是，怎么，如何在增加另一个通道。
  prefs: []
  type: TYPE_NORMAL
- en: 影响ESPN可以服务的GRPS总数，以下是调查结果，和，这可能会成为事后显而易见的发现之一，但可能事先不明显，也就是可以，如果你为你的公司推出一个移动频道，不一定是，espn，你肯定会蚕食你的其他频道。
  prefs: []
  type: TYPE_NORMAL
- en: 但我只想说，顺便说一句，这可能是移动销售，如果你在手机上卖得更多，你会在网上少卖吗，答案大概是，但让我说两件事关于第一个，你最好蚕食自己的销售额，比别人蚕食你的销售，其次，他们发现即使ESPN犯规。
  prefs: []
  type: TYPE_NORMAL
- en: 我通过分析发现这一点更普遍，即使移动频道确实部分地蚕食了你的其他频道，总体积实际上上升了，以及它为ESPN工作的方式，世界警察在一天内吃人，意思是，如果我在某一天花更多的时间在手机上。
  prefs: []
  type: TYPE_NORMAL
- en: 那天我打算少看电视。但总的来说，我给了你一个额外的渠道来与我的公司接触，这是当今分析的一个非常强大的应用领域，事实上，你可以通过多种渠道测量人们，如果你喜欢电视，移动网络流媒体视频，意味着什么是重要的。
  prefs: []
  type: TYPE_NORMAL
- en: 是全部订婚，你不必担心每个渠道的利润最大化，想象一下同样的事情在销售中也是如此，如果你有线上和线下销售，你不应该担心，如果我在线启动，这会蚕食我的商店吗，嗯，也许吧，但你应该关心的是总的盈利能力。
  prefs: []
  type: TYPE_NORMAL
- en: 这是两者之间的相互作用，只有通过改进的数据和分析，你能估计一下那个问题吗？嗯，下一个是什么嗯，如你所知，我是个超级高尔夫球迷，所以我花了很多时间想高尔夫，其中一个，这是一个问题，价格折扣有多值钱。
  prefs: []
  type: TYPE_NORMAL
- en: 我想用高尔夫的方式来回答这个问题，但这也是一个开创性的问题，今天通过分析被问到，所以这里有一个例子，很明显我叫埃里克，嗯，想象一下你给埃里克发了一个关于打高尔夫球的价格促销。
  prefs: []
  type: TYPE_NORMAL
- en: 假设我是一个对价格敏感的顾客，所以我打高尔夫更多，那倒是真的，所以你可以做的一件事是，你可以测量人的比例或人数，你寄优惠券，两个高尔夫折扣，你可以看到他们是否更多地打高尔夫。
  prefs: []
  type: TYPE_NORMAL
- en: 我的观点是这完全是错误的答案，而且会低估折扣的效果，现在的问题是为什么，大多数人不会一个人打高尔夫，例如，如果你给我打高尔夫球的折扣，我可能会更多地打高尔夫球，然后我会打电话给我的三个朋友，这是四人组。
  prefs: []
  type: TYPE_NORMAL
- en: 让我们都打好高尔夫球，不仅仅是为了我更多地打高尔夫，但对于我更多打高尔夫的朋友来说，有一项关于，如果你喜欢你的社交网络的价值，和，人们发现，大约三分之二的折扣价值往往是，对于您发送给的人。
  prefs: []
  type: TYPE_NORMAL
- en: 但大约三分之一的价值来自他们现在交谈的朋友，当然你怎么知道你知道，因为你必须有埃里克和谁谈过的数据，一旦你现在派他去，你从哪里得到的数据，你今天可以从Facebook上收集这些信息，实际上有公司在那里。
  prefs: []
  type: TYPE_NORMAL
- en: 我知道这听起来很恐怖，你可以把手机放在手机上的应用程序上，它实际上可以测量你的对话，你当然知道你注册了这个应用程序，但今天衡量口碑的能力，让我们对当今营销的价值有了更好的认识，同样。
  prefs: []
  type: TYPE_NORMAL
- en: 可能会有比其他客户更有价值的客户，这不仅仅是因为他们对营销的反应更多，而是因为他们告诉更多的朋友，换句话说，他们不仅将营销内化，他们把它外化给他们的朋友，所以好好想想，这些问题，你知道。
  prefs: []
  type: TYPE_NORMAL
- en: 我应该把营销功劳给谁，你知道，嗯，渠道互相蚕食吗，折扣的价值是什么，这些都是开创性的标记问题，直到最近，通过收集更好的数据，一些无法回答的问题，你可以把它们综合起来回答。
  prefs: []
  type: TYPE_NORMAL
- en: 但你永远无法在个人层面上衡量它们，我最后想说的是Facebook的投资回报率是多少，这可能是你们中许多人正在处理的一个问题，换句话说是更多的喜欢或提到有价值，我总是喜欢把它框起来，当然。
  prefs: []
  type: TYPE_NORMAL
- en: 谁不希望他们的产品更受欢迎呢，但我声称这是错误的商业问题，这就是为什么这是错误的商业问题，因为想象一个数据集，你不仅有赞，但你也有在线广告，有人看到了想象一下你也有电视广告，有人看到。
  prefs: []
  type: TYPE_NORMAL
- en: 想象一下你也有脸书，他们在Facebook上看到的想象一下你也有很好的购买数据，如果你对Facebook上的购买数据进行回归，我向你保证有更多喜欢产品的人，在脸书上点赞越多的人就会买得越多。
  prefs: []
  type: TYPE_NORMAL
- en: 但这不是问题所在，这不是Facebook值得的原因，截至今天的700亿，可能是750亿，明天八百亿，大多数人认为Facebook的信息收集，包含在线和电视数据，别告诉你，所以这意味着。
  prefs: []
  type: TYPE_NORMAL
- en: 如果我做了一个回归，试图预测购买，基于在线和电视，还包括脸书数据，Facebook将有一个显著的正系数，这意味着，即使我知道你在网上做了多少，即使我知道你看了多少电视广告。
  prefs: []
  type: TYPE_NORMAL
- en: 知道你在Facebook上看到了一个给定产品的多少赞，比传统的在线或电视广告更能帮助我预测购买数据，这就是客户属性和客户级别数据的魔力，如果你有这个数据，你就可以开始分解了，是电视吗，是脸书一遍又一遍。
  prefs: []
  type: TYPE_NORMAL
- en: 对于数据集，我的分析表明Facebook确实有预测能力，超越，只是传统广告，但解决这个问题的唯一方法是通过更好的数据，所以Facebook和在线有更大的短期影响，这部分可能并不奇怪，你可能感兴趣的部分。
  prefs: []
  type: TYPE_NORMAL
- en: 观看电视广告有更长期的影响，我的意思是，如果你看到Facebook广告，你在你的Facebook提要中看到一个赞，在您的新闻提要中，你可能会说，哦，我很高兴我的朋友喜欢这个产品。
  prefs: []
  type: TYPE_NORMAL
- en: 但五分钟十分钟后你可能就会忘记这件事，另一方面，电视的效果要长得多，对我们来说最迷人的部分，市场是有效的，我的意思是，如果一个电视广告的成本是Facebook广告的一千倍，电视广告的经济价值是。
  prefs: []
  type: TYPE_NORMAL
- en: Facebook广告的经济价值，意思是，基本上，在这些不同的渠道中，你花费的金额除以影响的金额基本上是不变的，我们对市场的效率感到惊讶。
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/3aaac3cbf8f98628a4e150fba24448e8_2.png)'
  prefs: []
  type: TYPE_IMG
